// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'album': string;
  'albumType': string;
  'allTracks': string;
  'info': string;
  'missingWanted': string;
  'tracks': string;
}
export const cssExports: CssExports;
export default cssExports;
