language: csharp
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - dos2unix
      - libchromaprint-tools
    update: true
  homebrew:
    packages:
      - yarn
      - dos2unix
    update: true
solution: src/Lidarr.sln
before_install:
  - nvm install 8
  - nvm use 8
script:
  - ./build.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./test.sh Mac Unit; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./test.sh Linux Unit; fi
