language: csharp
solution: src/Lidarr.sln
install:
  - nvm install 8
  - nvm use 8
script:
  - node --version
  - ./build.sh
  - chmod +x test.sh
  - ./test.sh Linux Unit
after_success:
  - chmod +x package.sh
  - ./package.sh
