version: '0.2.0.{build}'

assembly_info:
  patch: true
  file: 'src\NzbDrone.Common\Properties\SharedAssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

install:
  - git submodule update --init --recursive

build_script:
  - C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./build.sh
  
after_build:
  - C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./appveyor-package.sh
  - ps: Get-ChildItem .\_artifacts\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\_artifacts\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\_artifacts\*.tar.gz | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

test_script:
  - C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./test.sh Windows Unit

cache:
  - '%USERPROFILE%\.nuget\packages'
  - node_modules
  
pull_requests:
  do_not_increment_build_number: true

skip_branch_with_pr: true

on_failure:
  - ps: Get-ChildItem .\_artifacts\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\_artifacts\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\_artifacts\*.tar.gz | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

only_commits:
  files:
    - src/
    - osx/
    - gulp/
    - logo/
    - setup/
    - appveyor.yml
    - build-appveyor.cake
