# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - checkout: self
    submodules: true
  - task: Bash@3
    displayName: Build Lidarr
    inputs:
      targetType: 'filePath'
      filePath: ./build.sh
  - task: Bash@3
    displayName: Windows Unit Tests
    inputs:
      targetType: 'filePath'
      filePath: ./test.sh
      arguments: Windows Unit
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: '**/TestResult.xml'
      mergeTestResults: true
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - checkout: self
    submodules: true
  - task: Bash@3
    displayName: Build Lidarr
    inputs:
      targetType: 'filePath'
      filePath: ./build.sh
  - task: Bash@3
    displayName: Mac Unit Tests
    inputs:
      targetType: 'filePath'
      filePath: ./test.sh
      arguments: Mac Unit
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: '**/TestResult.xml'
      mergeTestResults: true
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - checkout: self
    submodules: true
  - task: Bash@3
    displayName: Build Lidarr
    inputs:
      targetType: 'filePath'
      filePath: ./build.sh
  - task: Bash@3
    displayName: Linux Unit Tests
    inputs:
      targetType: 'filePath'
      filePath: ./test.sh
      arguments: Linux Unit
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: '**/TestResult.xml'
      mergeTestResults: true
