# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  artifactsFolder: './_artifacts'

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - checkout: self
    submodules: true
  - task: Bash@3
    displayName: Build Lidarr
    inputs:
      targetType: 'filePath'
      filePath: ./build.sh
  - task: Bash@3
    displayName: Windows Unit Tests
    inputs:
      targetType: 'filePath'
      filePath: ./test.sh
      arguments: Windows Unit
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: '**/TestResult.xml'
      testRunTitle: 'Windows Unit Tests'
      mergeTestResults: true
  - task: ArchiveFiles@2
    displayName: Create Windows zip
    inputs:
      archiveFile: '$(artifactsFolder)/Lidarr.$(Build.SourceBranchName).$(Build.BuildId).windows.zip'
      archiveType: 'zip'
      includeRootFolder: false
      rootFolderOrFile: $(artifactsFolder)/windows
  - task: ArchiveFiles@2
    displayName: Create MacOS App
    inputs:
      archiveFile: '$(artifactsFolder)/Lidarr.$(Build.SourceBranchName).$(Build.BuildId).osx-app.zip'
      archiveType: 'zip'
      includeRootFolder: false
      rootFolderOrFile: $(artifactsFolder)/macos-app
  - task: ArchiveFiles@2
    displayName: Create MacOS tar
    inputs:
      archiveFile: '$(artifactsFolder)/Lidarr.$(Build.SourceBranchName).$(Build.BuildId).osx.tar.gz'
      archiveType: 'tar'
      tarCompression: 'gz'
      includeRootFolder: false
      rootFolderOrFile: $(artifactsFolder)/macos
  - task: ArchiveFiles@2
    displayName: Create Linux tar
    inputs:
      archiveFile: '$(artifactsFolder)/Lidarr.$(Build.SourceBranchName).$(Build.BuildId).linux.tar.gz'
      archiveType: 'tar'
      tarCompression: 'gz'
      includeRootFolder: false
      rootFolderOrFile: $(artifactsFolder)/linux
  - bash: |
      export APPVEYOR_BUILD_NUMBER=${BUILD_BUILDNUMBER}
      export APPVEYOR_BUILD_VERSION=${BUILD_BUILDID}
      export APPVEYOR_REPO_BRANCH=${BUILD_SOURCEBRANCHNAME}
      ./setup/inno/ISCC.exe "./setup/lidarr.iss"
      cp ./setup/output/Lidarr.*windows.exe ${ARTIFACTSFOLDER}/Lidarr.${BUILD_SOURCEBRANCHNAME}.${BUILD_BUILDID}.windows-installer.exe
    displayName: Create windows installer
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(artifactsFolder)'
      ArtifactName: 'lidarr'
      publishLocation: 'Container'
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - checkout: self
    submodules: true
  - task: Bash@3
    displayName: Build Lidarr
    inputs:
      targetType: 'filePath'
      filePath: ./build.sh
  - task: Bash@3
    displayName: Mac Unit Tests
    inputs:
      targetType: 'filePath'
      filePath: ./test.sh
      arguments: Mac Unit
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: '**/TestResult.xml'
      testRunTitle: 'Mac Unit Tests'
      mergeTestResults: true
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  # install chromaprint from github since the 16.04 version is ancient
  - script: |
      wget https://github.com/acoustid/chromaprint/releases/download/v1.4.3/chromaprint-fpcalc-1.4.3-linux-x86_64.tar.gz
      sudo tar xf chromaprint-fpcalc-1.4.3-linux-x86_64.tar.gz --strip-components=1 --directory /usr/bin
    displayName: Install fpcalc
  - checkout: self
    submodules: true
  - task: Bash@3
    displayName: Build Lidarr
    inputs:
      targetType: 'filePath'
      filePath: ./build.sh
  - task: Bash@3
    displayName: Linux Unit Tests
    inputs:
      targetType: 'filePath'
      filePath: ./test.sh
      arguments: Linux Unit
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: '**/TestResult.xml'
      testRunTitle: 'Linux Unit Tests'
      mergeTestResults: true
