# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - checkout: self
    submodules: true
  - task: Bash@3
    inputs:
      targetType: 'filePath'
      filePath: ./build.sh
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - checkout: self
    submodules: true
  - task: Bash@3
    inputs:
      targetType: 'filePath'
      filePath: ./build.sh
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - checkout: self
    submodules: true
  - task: Bash@3
    inputs:
      targetType: 'filePath'
      filePath: ./build.sh
- job: Unit Test Windows
  dependsOn: Windows
  pool:
    vmImage: 'vs2017-win2016'
  - task: Bash@3
    inputs:
      targetType: 'filePath'
      filePath: ./test.sh Windows Unit
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: '**/myresults.xml'
      mergeTestResults: true
