// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'albumCount': string;
  'albumType': string;
  'albumTypeLabel': string;
  'artistName': string;
  'container': string;
  'disambiguation': string;
  'expandButton': string;
  'header': string;
  'info': string;
  'left': string;
  'modalFooter': string;
  'name': string;
  'overview': string;
  'poster': string;
  'searchForNewAlbumContainer': string;
  'searchForNewAlbumInput': string;
  'searchForNewAlbumLabel': string;
  'searchForNewAlbumLabelContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
