// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backStar': string;
  'frontStar': string;
  'starRating': string;
}
export const cssExports: CssExports;
export default cssExports;
