// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'artistName': string;
  'foreignArtistId': string;
}
export const cssExports: CssExports;
export default cssExports;
