// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'downloadClient': string;
  'downloadClients': string;
  'downloadClientsHeader': string;
  'editButton': string;
  'fillcolumn': string;
  'headerActions': string;
  'headerFillcolumn': string;
  'headerName': string;
  'horizontalScroll': string;
  'name': string;
}
export const cssExports: CssExports;
export default cssExports;
