// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'expandButton': string;
  'expandButtonIcon': string;
  'fileDetails': string;
  'filename': string;
  'header': string;
  'medium': string;
}
export const cssExports: CssExports;
export default cssExports;
