// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'audioTags': string;
  'filename': string;
}
export const cssExports: CssExports;
export default cssExports;
