// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'taggingProfileDragSource': string;
  'taggingProfilePlaceholder': string;
  'taggingProfilePlaceholderAfter': string;
  'taggingProfilePlaceholderBefore': string;
}
export const cssExports: CssExports;
export default cssExports;
