// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'addButton': string;
  'addTaggingProfile': string;
  'fillcolumn': string;
  'horizontalScroll': string;
  'name': string;
  'optionColumn': string;
  'taggingProfiles': string;
  'taggingProfilesHeader': string;
  'writeAudioTags': string;
}
export const cssExports: CssExports;
export default cssExports;
