// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bulkSelect': string;
  'errorMessage': string;
  'filterContainer': string;
  'filterText': string;
  'footer': string;
  'importMode': string;
  'progressContainer': string;
  'progressFill': string;
  'progressFillError': string;
  'progressHeader': string;
  'progressTrack': string;
  'leftButtons': string;
  'rightButtons': string;
}
export const cssExports: CssExports;
export default cssExports;
