// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'actionMenuIcon': string;
  'actions': string;
  'actionsMenu': string;
  'actionsMenuContent': string;
  'collapseButtonContainer': string;
  'expandButton': string;
  'expandButtonIcon': string;
  'header': string;
  'left': string;
  'medium': string;
  'mediumFormat': string;
  'mediumNumber': string;
  'noTracks': string;
  'tracks': string;
}
export const cssExports: CssExports;
export default cssExports;
