// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'audio': string;
  'customFormatScore': string;
  'duration': string;
  'indexerFlags': string;
  'monitored': string;
  'size': string;
  'status': string;
  'title': string;
  'trackNumber': string;
}
export const cssExports: CssExports;
export default cssExports;
