// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'delayProfile': string;
  'name': string;
  'tags': string;
}
export const cssExports: CssExports;
export default cssExports;
