// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'artistName': string;
  'foreignId': string;
  'importListExclusion': string;
}
export const cssExports: CssExports;
export default cssExports;
