// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'container': string;
  'disambiguation': string;
  'info': string;
  'modalFooter': string;
  'name': string;
  'overview': string;
  'poster': string;
  'searchForMissingAlbumsContainer': string;
  'searchForMissingAlbumsInput': string;
  'searchForMissingAlbumsLabel': string;
  'searchForMissingAlbumsLabelContainer': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
