// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'absoluteEpisodeNumber': string;
  'albumInfo': string;
  'albumTitle': string;
  'artistName': string;
  'downloaded': string;
  'downloading': string;
  'event': string;
  'info': string;
  'missing': string;
  'statusIcon': string;
  'unmonitored': string;
  'unreleased': string;
}
export const cssExports: CssExports;
export default cssExports;
