// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'downloaded': string;
  'downloading': string;
  'legendItem': string;
  'missing': string;
  'onAir': string;
  'partial': string;
  'unmonitored': string;
  'unreleased': string;
}
export const cssExports: CssExports;
export default cssExports;
