// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'addButton': string;
  'addDelayProfile': string;
  'delayProfiles': string;
  'delayProfilesHeader': string;
  'fillcolumn': string;
  'horizontalScroll': string;
  'name': string;
}
export const cssExports: CssExports;
export default cssExports;
