// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'headerContainer': string;
  'headerDelay': string;
  'headerTitle': string;
  'qualities': string;
}
export const cssExports: CssExports;
export default cssExports;
