// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'downloadProtocolItemDragSource': string;
  'downloadProtocolItemPlaceholder': string;
  'downloadProtocolItemPlaceholderAfter': string;
  'downloadProtocolItemPlaceholderBefore': string;
}
export const cssExports: CssExports;
export default cssExports;
