// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'monitorToggle': string;
  'status': string;
  'statusIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
