// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'added': string;
  'albumCount': string;
  'artistType': string;
  'banner': string;
  'bannerGrow': string;
  'bannerImage': string;
  'cell': string;
  'checkInput': string;
  'genres': string;
  'lastAlbum': string;
  'link': string;
  'metadataProfileId': string;
  'monitorNewItems': string;
  'nextAlbum': string;
  'overlayTitle': string;
  'path': string;
  'qualityProfileId': string;
  'ratings': string;
  'sizeOnDisk': string;
  'sortName': string;
  'status': string;
  'tags': string;
  'trackCount': string;
  'trackProgress': string;
  'useSceneNumbering': string;
}
export const cssExports: CssExports;
export default cssExports;
