// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'bannerContainer': string;
  'container': string;
  'content': string;
  'controls': string;
  'ended': string;
  'link': string;
  'nextAlbum': string;
  'overlayTitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
