// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alternateTitlesIconContainer': string;
  'artistNavigationButton': string;
  'artistNavigationButtons': string;
  'backdrop': string;
  'backdropOverlay': string;
  'contentContainer': string;
  'details': string;
  'detailsLabel': string;
  'errorMessage': string;
  'header': string;
  'headerContent': string;
  'info': string;
  'innerContentBody': string;
  'links': string;
  'metadataMessage': string;
  'monitorToggleButton': string;
  'overview': string;
  'path': string;
  'poster': string;
  'qualityProfileName': string;
  'runtime': string;
  'sizeOnDisk': string;
  'tags': string;
  'title': string;
  'titleContainer': string;
  'titleRow': string;
  'toggleMonitoredContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
