// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'collapseButtonContainer': string;
  'expandButton': string;
  'expandButtonIcon': string;
  'header': string;
  'left': string;
  'rankingHelp': string;
  'selectionCount': string;
  'songs': string;
  'title': string;
  'tracks': string;
}
export const cssExports: CssExports;
export default cssExports;
