// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'actionMenuIcon': string;
  'actions': string;
  'actionsMenu': string;
  'actionsMenuContent': string;
  'albumCount': string;
  'albumCountTooltip': string;
  'albumType': string;
  'albumTypeLabel': string;
  'albums': string;
  'collapseButtonContainer': string;
  'collapseButtonIcon': string;
  'expandButton': string;
  'expandButtonIcon': string;
  'header': string;
  'left': string;
  'noAlbums': string;
  'sizeOnDisk': string;
}
export const cssExports: CssExports;
export default cssExports;
